site_name: AI course

repo_url: https://github.com/maloyan/knowledge_doc/

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: 
        - en
        - ru

nav:
  - 1 Math: math.md
  - 2 Probability & Statistics: probability.md
  - 3 Machine Learning: ml.md
  - 4 Deep Learning: nn.md
  - 5 Neural Net Architectures: nn_architectures.md
  - 6 Natural Language Processing: nlp.md
  - 7 Computer Vision: cv.md
  - 8 Image Generation: image_generation.md
  - 9 Multimodal Modeling: multimodal.md
  - 10 Signal Processing: signal.md
  - 11 Reinforcement Learning: rl.md
  - 12 Interpretation: interpretation.md
  - 13 Graph NN: graph.md
  - 14 Robustness: robustness.md
  - Exam questions: exam.md
  